### ISSUE TITLE
simple-mtpfs mounts android ok but file sizes are wrong

### ISSUE THREAD

**Issue by press0** [phatina/simple-mtpfs#16]
example:

download install simple-mtpfs from head
cd /mnt
mkdir android
simple-mtpfs android
Unable to open ~/.mtpz-data for reading, MTPZ disabled.

du -b /mnt/android/DCIM/Camera/IMG_20131013_081500.jpg
749356
Image viewer error: Application transferred too few scanlines

bittorrentsync file transfer:
du -b /mnt/bittorrentsync/Camera/IMG_20131013_081500.jpg
749387 
Image viewed ok

hope this helps,

Ubuntu 13.10 | x86_64
Nexus 4 | Android 4.3

**Comment by EskeRahn** [comment]
I know this is a VERY old thread, but the bug is still there, and it seems to be a quite elusive one.
I had provoked it moving some filed to SD, regretting and moved them back again.
Moving them to a new place and back on internal memory remedied it, See more elaborate description here: http://eskerahn.dk/wordpress/?p=1948
